# Generated by Django 2.1.5 on 2019-02-15 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvotes', models.FloatField(default=0)),
                ('downvotes', models.FloatField(default=0)),
                ('published_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.Metadata')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.Metadata'),
        ),
    ]
